export { createXyncraPlugin, XyncraClientKey } from './plugin'
export type { ConnectionStatus as XyncraConnectionStatus, XyncraPluginOptions } from './plugin'
export { useXyncra } from './composables/useXyncra'
export { useRegisterFunctions } from './composables/useRegisterFunctions'
export type { FunctionEntry } from './composables/useRegisterFunctions'
export { defineTestHelpers } from './defineTestHelpers'
export type { HelperDef, Helpers, DefineTestHelpersOptions } from './defineTestHelpers'
export { useStreaming } from './composables/useStreaming'
export type { UseStreamingReturn } from './composables/useStreaming'
export { useHITL } from './composables/useHITL'
export type { HITLQuestion, UseHITLReturn } from './composables/useHITL'
export { useConversations } from './composables/useConversations'
export type { UseConversationsReturn } from './composables/useConversations'
export { useMessages } from './composables/useMessages'
export type { UseMessagesReturn } from './composables/useMessages'
export { VueUpdateHandler } from './internal/VueUpdateHandler'
export { FunctionRegistry } from './internal/FunctionRegistry'
export type { FunctionHandler } from './internal/FunctionRegistry'
export { TypedEventEmitter } from './internal/EventEmitter'
export { BrowserWebSocketFactory, BrowserWebSocketAdapter } from './adapters/websocket'
export { BrowserIndexedDBProvider } from './adapters/indexeddb'
export { ConsoleLogger } from './adapters/logger'
export { default as FloatingAssistant } from './components/FloatingAssistant.vue'
export { default as ConnectionStatus } from './components/ConnectionStatus.vue'
export { default as ChatPanel } from './components/ChatPanel.vue'
export { default as FunctionCallDisplay } from './components/FunctionCallDisplay.vue'
export { default as HITLDialog } from './components/HITLDialog.vue'
export { default as AgentStatusIndicator } from './components/AgentStatusIndicator.vue'
export { generalFunctions } from './functions/general'
