package tracing

// Span names used throughout Xyncra Server.
const (
	SpanWSConnection        = "ws.connection"
	SpanWSMessageReceive    = "ws.message.receive"
	SpanHandlerInvoke       = "handler.invoke"
	SpanBrokerEnqueue       = "handler.broker.enqueue"
	SpanBrokerProcess       = "mq.process"
	SpanHandlerBroadcast    = "handler.broadcast"
	SpanAgentExecute        = "agent.execute"
	SpanAgentBuild          = "agent.build"
	SpanAgentRun            = "agent.run"
	SpanAgentLLMCall        = "agent.llm.call"
	SpanAgentToolCall       = "agent.tool.call"
	SpanAgentCheckpointSave = "agent.checkpoint.save"
	SpanAgentStream         = "agent.stream"
)

// DB layer span names (GORM store methods).
const (
	SpanDBConversationCreate               = "db.conversation.create"
	SpanDBConversationGet                  = "db.conversation.get"
	SpanDBConversationGetByUsers           = "db.conversation.get_by_users"
	SpanDBConversationGetByUser            = "db.conversation.get_by_user"
	SpanDBConversationUpdate               = "db.conversation.update"
	SpanDBConversationDelete               = "db.conversation.delete"
	SpanDBConversationRestore              = "db.conversation.restore"
	SpanDBConversationUpdateLastMessage    = "db.conversation.update_last_message"
	SpanDBConversationSearchByTitle        = "db.conversation.search_by_title"
	SpanDBConversationGetUnscoped          = "db.conversation.get_unscoped"
	SpanDBConversationUpdateLastRead       = "db.conversation.update_last_read"
	SpanDBConversationUpdateAgentStatus    = "db.conversation.update_agent_status"
	SpanDBConversationClearAgentStatus     = "db.conversation.clear_agent_status"
	SpanDBConversationListStaleHITL        = "db.conversation.list_stale_hitl"
	SpanDBMessageCreate                    = "db.message.create"
	SpanDBMessageGet                       = "db.message.get"
	SpanDBMessageListByConversation        = "db.message.list_by_conversation"
	SpanDBMessageDelete                    = "db.message.delete"
	SpanDBMessageGetByClientMessageID      = "db.message.get_by_client_message_id"
	SpanDBMessageSearchByConversation      = "db.message.search_by_conversation"
	SpanDBMessageListByTimeRange           = "db.message.list_by_time_range"
	SpanDBMessageRestore                   = "db.message.restore"
	SpanDBMessageDeleteByConversation      = "db.message.delete_by_conversation"
	SpanDBMessageCountUnread               = "db.message.count_unread"
	SpanDBMessageRestoreByConversation     = "db.message.restore_by_conversation"
	SpanDBMessageListRecentByConversation  = "db.message.list_recent_by_conversation"
	SpanDBUserUpdateCreate                 = "db.user_update.create"
	SpanDBUserUpdateListByUser             = "db.user_update.list_by_user"
	SpanDBUserUpdateListByUserRange        = "db.user_update.list_by_user_range"
	SpanDBUserUpdateGetLatestSeq           = "db.user_update.get_latest_seq"
	SpanDBUserUpdateCleanupExpiredBefore   = "db.user_update.cleanup_expired_before"
	SpanDBRemoteCallingCreate                   = "db.remote_calling.create"
	SpanDBRemoteCallingGetByID                  = "db.remote_calling.get_by_id"
	SpanDBRemoteCallingGetPendingByConversation = "db.remote_calling.get_pending_by_conversation"
	SpanDBRemoteCallingGetPendingByCheckpoint   = "db.remote_calling.get_pending_by_checkpoint"
	SpanDBRemoteCallingGetByCheckpoint          = "db.remote_calling.get_by_checkpoint"
	SpanDBRemoteCallingResolveResult            = "db.remote_calling.resolve_result"
	SpanDBRemoteCallingResolveError             = "db.remote_calling.resolve_error"
	SpanDBRemoteCallingCancelByCheckpoint       = "db.remote_calling.cancel_by_checkpoint"
	SpanDBRemoteCallingDeleteByConversation     = "db.remote_calling.delete_by_conversation"
	SpanDBRemoteCallingDeleteByCheckpoint       = "db.remote_calling.delete_by_checkpoint"
	SpanDBRemoteCallingCountPendingByCheckpoint = "db.remote_calling.count_pending_by_checkpoint"
	SpanDBRemoteCallingListExpired              = "db.remote_calling.list_expired"
	SpanDBRemoteCallingMarkExpired              = "db.remote_calling.mark_expired"
	SpanDBStoreSendMessage                 = "db.store.send_message"
	SpanDBStoreTransaction                 = "db.store.transaction"
	SpanDBStoreBeginTx                     = "db.store.begin_tx"
	SpanDBStoreAutoMigrate                 = "db.store.auto_migrate"
	SpanDBStorePing                        = "db.store.ping"
	SpanDBStoreHealthCheck                 = "db.store.health_check"
)

// Redis layer span names.
const (
	SpanRedisConnectionAdd          = "redis.connection.add"
	SpanRedisConnectionGet          = "redis.connection.get"
	SpanRedisConnectionRemove       = "redis.connection.remove"
	SpanRedisConnectionExists       = "redis.connection.exists"
	SpanRedisConnectionUpdate       = "redis.connection.update"
	SpanRedisConnectionPatch        = "redis.connection.patch"
	SpanRedisConnectionRefresh      = "redis.connection.refresh"
	SpanRedisConnectionListByUser   = "redis.connection.list_by_user"
	SpanRedisConnectionCountByUser  = "redis.connection.count_by_user"
	SpanRedisConnectionCountAll     = "redis.connection.count_all"
	SpanRedisConnectionRemoveByUser = "redis.connection.remove_by_user"
	SpanRedisConnectionPing         = "redis.connection.ping"
	SpanRedisPendingSave            = "redis.pending.save"
	SpanRedisPendingList            = "redis.pending.list"
	SpanRedisPendingRemove          = "redis.pending.remove"
	SpanRedisPendingUpdate          = "redis.pending.update"
	SpanRedisPendingRemoveByDevice  = "redis.pending.remove_by_device"
	SpanRedisBroadcasterPublish     = "redis.broadcaster.publish"
	SpanRedisBroadcasterSubscribe   = "redis.broadcaster.subscribe"
)

// Attribute keys for span attributes.
const (
	AttrUserID         = "xyncra.user.id"
	AttrDeviceID       = "xyncra.device.id"
	AttrConnID         = "xyncra.connection.id"
	AttrMethod         = "xyncra.method"
	AttrAgentID        = "xyncra.agent.id"
	AttrConversationID = "xyncra.conversation.id"
	AttrTaskType       = "xyncra.task.type"
	AttrTaskID         = "xyncra.task.id"
	AttrIteration      = "xyncra.iteration"
	AttrToolName       = "xyncra.tool.name"
	AttrModel          = "xyncra.llm.model"
	AttrInputTokens    = "xyncra.llm.input_tokens"
	AttrOutputTokens   = "xyncra.llm.output_tokens"
	AttrTotalTokens    = "xyncra.llm.total_tokens"
	AttrDurationMs     = "xyncra.duration_ms"
	AttrCheckpointID   = "xyncra.checkpoint.id"
	AttrChunkCount     = "xyncra.chunk_count"
	AttrTotalChars     = "xyncra.total_chars"
	AttrDebug          = "xyncra.debug"
	AttrSizeBytes      = "xyncra.size_bytes"
	AttrTargetUserID   = "xyncra.target_user_id"
	AttrTargetType     = "xyncra.target_type"
)
